[tool.black]
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']
line-length = 100
exclude = '''
(
    \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.eggs\/
    | build
    | dist
    | tutorials
    | venv\/
    | test_serde_full\.py
    | third_party
)
'''
